### ISSUE TITLE
Uploading any file/dir

### ISSUE THREAD

**Issue by Frityet** [lights0123/n-link#5]
Could there be functionality to install any folder/dir onto the device, not just .tns?

**Comment by lights0123** [comment]
I've thought about doing that, but I couldn't decide what it should do in each case.

File that doesn't end in .tns:
- rename to add it and go?
- if it's a zip file, should it unzip it?
  - if so, what should it do to files without a .tns in it?
    - Skip them? That could be helpful if someone downloads a program from e.g. TI-Planet which often has the binary mixed with source files.
    - Rename them?

**Comment by Frityet** [comment]
> rename to add it and go?
Like rename it to a .tns? how could it then even be used on softwares, such as the SNES emulator

>if it's a zip file, should it unzip it? 
yeah probs, I dont see any program which needs a zipped directory

>if so, what should it do to files without a .tns in it? 
well, I just see it beneficial if any file/dir could be loaded on

**Comment by Frityet** [comment]
Downloading everything required for building rn, gonna see what I can do.

**Comment by Frityet** [comment]
Conclusion from looking at devices.ts: I know jack shit about typescript/javascript/vue

**Comment by Frityet** [comment]
ok, so, I removed the .tns limit, testing now

**Comment by lights0123** [comment]
The calculator isn't going to let you send a file without a tns extension or rename an existing file to remove it IIRC

**Comment by Frityet** [comment]
;( there goes my dreams then

**Comment by Frityet** [comment]
wait. how do I rename files on the calc?

**Comment by lights0123** [comment]
Ctrl+Menu → Rename...

But, of course, it hides the tns extension and doesn't let you remove it.

---

what software are you using that needs files that *don't* have a tns extension? And if you truly do, you can use a Ndless file manager app to rename it.

**Comment by Frityet** [comment]
I want to install ROMs so I can "do math" in class

**Comment by lights0123** [comment]
Right, but don't all the emulators expect ROMs ending in their file extension + .tns?

**Comment by Frityet** [comment]
I don't know tbh, will try the rename method

**Comment by lights0123** [comment]
The only software that can remove the tns extension is an Ndless program—you can't do it over USB, and the stock file browser hides the tns extension so you can't remove it, and *hides files that don't have a tns extension at all*.

Have you tried just... leaving the tns extension on? It wouldn't make sense for an emulator to not support running from a .tns file because then you couldn't see it in the stock file manager.
